environment:
  psg_api_key:
    secure: /lJyGquwMRUqVDnml40Oe0idMigX/55GQOR6aKqjjmAlnLrJUnViRdW/4Zp1u43X


# Allow WMF5 (i.e. PowerShellGallery functionality)
#os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
- ps: . .\build.ps1
- ps: Get-PSRepository
- ps: Find-Module PSProofpoint
- ps: (Get-Content .\PSProofpoint\PSProofpoint.psd1).replace('<BUILD_VERSION>', $env:APPVEYOR_BUILD_VERSION) | Set-Content .\PSProofpoint\PSProofpoint.psd1
- ps: mkdir $env:userprofile\Documents\WindowsPowerShell\Modules\PSProofpoint
- ps: Copy-Item .\PSProofpoint\* $env:userprofile\Documents\WindowsPowerShell\Modules\PSProofpoint\ -Recurse -Force
- ps: Publish-Module -Name PSProofpoint -NuGetApiKey $env:psg_api_key
- ps: Remove-Item $env:userprofile\Documents\WindowsPowerShell\Modules\PSProofpoint -Recurse -Force
- ps: Write-Host "Wait for 30 seconds until the module is published"; Start-Sleep -s 30
- ps: Find-Module PSProofpoint
- ps: Install-Module PSProofpoint -Scope AllUsers
- ps: Get-PackageProvider
- ps: Get-Module
- ps: Write-Host "Wait for 30 seconds until the module is published"; Start-Sleep -s 30
- ps: dir $env:ProgramFiles\WindowsPowerShell\Modules\PSProofpoint\
notifications:

  # Email
  - provider: Email
    to:
      - nick.lepore@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true

# Install NuGet to interact with the PowerShell Gallery
install:
- ps: |
    Install-PackageProvider -Name NuGet -Force | Out-Null
    Install-Module -Name Pester -Force
    Install-Module -Name posh-git -Force

